### ISSUE TITLE
Replace Pi using Recursion using CPP.

### ISSUE THREAD

**Issue by Stanish4Ever** [TECHOUS/AlgoHeist#232]
A recursion question in which each occurence of Pi in a string gets replaced with 3.15
Example:
Input: fbpix
Output: fb3.14x

I would like to solve this problem in CPP.

I can also solve this problem in Python. I would love to add a Python code for the same. 

I would request you to assign me this issue.
Thank you.

**Comment by GauravWalia19** [comment]
Hi, Thanks for raising an issue first, what will be algorithm you are using here

**Comment by Stanish4Ever** [comment]
> Hi, Thanks for raising an issue first, what will be algorithm you are using here

I'm gonna use the fundamentals of recursion to solve this problem.
Not any specific algorithm but it will give clarity on recursion.

**Comment by GauravWalia19** [comment]
It doesn't seems to be right as we are looking for algorithm.
