### ISSUE TITLE
Max product subarray and max sum subarray in array of integers.

### ISSUE THREAD

**Issue by stubborn-1508** [TechOUs/AlgoHeist#235]
I would like to add the code using kadane's algorithm with a little variation in case of finding product.

**Comment by GauravWalia19** [comment]
Which language you will be submitting the code

**Comment by Harsh8084** [comment]
I will submit the code in c++
Kindly assign it to me.

**Comment by stubborn-1508** [comment]
I will be submitting the code in C++. Sorry for the late response .Please can you assign it to me under the label hacktoberfest.
