### ISSUE TITLE
Add Kadane Algorithm(use to find max subarray sum) in cpp 

### ISSUE THREAD

**Issue by Tasmiya-k** [TechOUs/AlgoHeist#236]
**Is your feature request related to a problem? Please describe.**
Want to add kadane's Algorithm in c++
**Describe the solution you'd like**
I'll push commented code of this algorithm

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by GauravWalia19** [comment]
It is already added here 
`/misc/kadane_algorithm/kadane.cpp`
